### PR TITLE
Minor code refactoring without changing the mechanics of the game.

### PR DESCRIPTION
**Pull request by RimuruDev**

### CODE REVIEW

**Comment by arkaht** [comment]
I appreciate your help but these changes are against my code style which I do not want to change for this project. Also, this project is commissioned by our school for Sunday, so we rush the deadline you know..

Plus, the code split into functions for the `HandUI.Update` will break its validity checks

**Comment by RimuruDev** [comment]
Good. Sorry for the input.

**Review by RimuruDev — COMMENTED** [review]
Separating into methods was a bad decision in this case.

**Comment by arkaht** [comment]
Yes, no problem! 

Sorry but I'll have to close this issue for these reasons :/

**Pull request closed without merging**
